[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#0E75F6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8FB"
textColor = "#0A0A0A"
font = "sans serif"

